const educationData = [
  {
    school: "St. Joseph's Catholic High School",
    duration: "Jul 2016 - May 2022",
    desc: "During my time at St. Joseph's Catholic High School, I studied A-Levels in Business, Computing, and Economics, developing a strong foundation in each subject. In Business, I focused on key concepts such as marketing, finance, and operations management, enhancing my problem-solving and strategic thinking through practical projects. Computing provided me with knowledge of programming, algorithms, and systems design, strengthening my coding and software development skills. Economics deepened my understanding of economic theories and market dynamics, while honing my analytical skills through case studies and real-world applications.",
    courses: [
      { courseName: "Business Studies", courseType: "A-Level", grade: "A" },
      { courseName: "Economics", courseType: "A-Level", grade: "C" },
      { courseName: "Computer Science", courseType: "A-Level", grade: "B" },
      { courseName: "Polish", courseType: "A-Level", grade: "C" },
      { courseName: "Polish", courseType: "AS", grade: "A" },
      { courseName: "Core Maths", courseType: "AS", grade: "B" },
      { courseName: "Computer Science", courseType: "GCSE", grade: "B" },
      { courseName: "Business Studies", courseType: "GCSE", grade: "B" },
      { courseName: "Geography", courseType: "GCSE", grade: "B" },
      { courseName: "RE", courseType: "GCSE", grade: "B" },
      { courseName: "Maths", courseType: "GCSE", grade: "B" },
      { courseName: "English Lang. & Lit.", courseType: "GCSE", grade: "B" },
      { courseName: "Chemistry", courseType: "GCSE", grade: "B" },
      { courseName: "Physics", courseType: "GCSE", grade: "B" },
      { courseName: "Biology", courseType: "GCSE", grade: "B" },
    ],
    totalGCSE: "10",
  },
  {
    school: "WBS Coding School",
    duration: "Sept 2022 - Jan 2023",
    desc: "Completed a bootcamp in Full-Stack Web Development, where I gained proficiency in both front-end and back-end technologies, including HTML, CSS, JavaScript, and frameworks such as React and Node.js. During the program, I collaborated on several projects with peers, utilizing version control systems like Git to manage code efficiently and facilitate teamwork. This hands-on experience not only enhanced my coding skills but also deepened my understanding of user experience design, database management, and RESTful APIs, preparing me for real-world development challenges.",
    courses: [
      { courseName: "UX/UI Design", grade: "Passed" },
      { courseName: "Git", grade: "Passed" },
      { courseName: "JavaScript", grade: "Passed" },
      { courseName: "React", grade: "Passed" },
      { courseName: "APIs", grade: "Passed" },
      { courseName: "SQL", grade: "Passed" },
      { courseName: "MongoDB", grade: "Passed" },
      { courseName: "NodeJS", grade: "Passed" },
      { courseName: "ExpressJS", grade: "Passed" },
      { courseName: "Security", grade: "Passed" },
      { courseName: "AI", grade: "Passed" },
    ],
  },
];

export default educationData;
